### ISSUE TITLE
Design image template and output.

### ISSUE THREAD

**Issue by Freyert** [Freyert/reddit_covid#1]
Currently trying to emulate the following image, but with NC state data from _The COVID Tracking Project_:

![image](https://user-images.githubusercontent.com/449155/86406789-c4655600-bc81-11ea-9fdc-b2c28eeae2db.png)

**Comment by Freyert** [comment]
What I have so far:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/449155/86471349-32099480-bd0b-11ea-8ed5-0221d476204b.png">

See `build_image` and `draw_header` in `present.py`

**Comment by Freyert** [comment]
Graph is now showing pct_increase over 2 week periods.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/449155/86479641-85cfaa00-bd1a-11ea-800f-0ee9a88f7752.png">

**Comment by ktrzonkowski** [comment]
Current WIP of trying to translate the original template to Python:

![image](https://user-images.githubusercontent.com/1671837/86494678-27b7bc80-bd44-11ea-9ff2-577a91f2e37d.png)

**Comment by Freyert** [comment]
Oooh! I like that. I significantly altered the graph because I was getting really confused about what exactly is being calculated in the original graph.

You'll have a good bit to merge in, but I think keeping things on a periodic basis will be super helpful.

The font is much better! And I think you matched the color better. I'd like to keep this color scheme you're working with. I changed everything to pink, but just look for hex codes.

**Comment by ktrzonkowski** [comment]
Pulling the changes in and starting day 2 of template!  (and fixing the rogue "in" that I don't know why I added)

Regarding confused about what is exactly being calculated in the original graph, which data metric are the numbers below the subheadings?  😅  Is it # of new cases within those two weeks?  That's what I assumed but I try to avoid assuming.

**Comment by ktrzonkowski** [comment]
Current WIP:

![image](https://user-images.githubusercontent.com/1671837/86515507-47ec8780-bde7-11ea-9f75-8d566d206a14.png)

I don't feel like I'm calculating the totals right, but I'll be the first to confess the highest level math I took was "what is 70/100 in percent form" ...

Which elements from the original do you still want to include?  The change from prior period %?  Source?  And do you want to use the original blue for the graph, or something else?

[edit: I am incapable of getting the dates in the right order for some reason]

**Comment by Freyert** [comment]
@ktrzonkowski now that I have a better understanding of the original graph I think keeping it as a target is great.


The two header numbers being the sum of new cases added the past 14 week rolling window and the sum of the cases added the current 2 week rolling window.

Then we just calculate the percent difference of those two sums.

The graph still mystifies me a big what they are calculating. I'm assuming it's historical rolling pct change, but I'm not sure.
